# Generated by Django 2.2.7 on 2019-11-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191125_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtask',
            name='complete_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='complete_date',
            field=models.DateTimeField(),
        ),
    ]
