# Generated by Django 2.2.7 on 2019-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(max_length=80)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=40)),
                ('status', models.BinaryField(default=True)),
                ('title', models.TextField(default=models.TextField(max_length=80), max_length=80)),
                ('meta_description', models.TextField(default=None, max_length=160)),
                ('meta_keywords', models.TextField(default=None, max_length=160)),
                ('pubtime', models.DateTimeField()),
                ('available_from', models.DateTimeField(default=None)),
                ('available_till', models.DateTimeField(default=None)),
            ],
        ),
    ]
