# Generated by Django 2.2.7 on 2019-12-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191126_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='pubtime',
            new_name='pubdate',
        ),
    ]
